### ISSUE TITLE
倒在了最后一步上

### ISSUE THREAD

**Issue by catunderthedusk** [shellfeel/Ant-AntV#11]
我是看到大表哥的文章，用到的，环境是kali，只装了cs4.0和pentbox1.8以及搜狗输入法.
通过了requirements的检测，但是在实验时有个问题，用不了pyinstaller打包。
具体字段如下：/bin/sh: 1: pyinstaller.exe: not found
想问一下，有没有什么解决办法？

**Comment by catunderthedusk** [comment]
2023-01-11 18:05:31.260 | ERROR    | __main__:exec_cmd:26 - 出错啦
2023-01-11 18:05:31.261 | ERROR    | __main__:exec_cmd:27 - /bin/sh: 1: pyinstaller.exe: not found

**Comment by catunderthedusk** [comment]
仔细研究了一下，感觉跟这篇文章有关：https://blog.csdn.net/Amaris_1997/article/details/112260136，
不过水平有限，可能判断错误，还是求大佬指点一下

**Comment by catunderthedusk** [comment]
在次实验，经过仔细比较，虽然在kali普通用户下启动检测程序不会报错，但最后好像也么有提示成功。
具体显示如下：
pip install -r requirements.txt  
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: altgraph==0.17.2 in /home/jokergamer/.local/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (0.17.2)
Requirement already satisfied: colorama==0.4.5 in /home/jokergamer/.local/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (0.4.5)
Requirement already satisfied: future==0.18.2 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (0.18.2)
Requirement already satisfied: loguru==0.6.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (0.6.0)
Requirement already satisfied: macholib==1.16 in /home/jokergamer/.local/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (1.16)
Requirement already satisfied: pefile==2022.5.30 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 6)) (2022.5.30)
Requirement already satisfied: psutil==5.9.1 in /home/jokergamer/.local/lib/python3.10/site-packages (from -r requirements.txt (line 7)) (5.9.1)
Requirement already satisfied: pycryptodome==3.15.0 in /home/jokergamer/.local/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (3.15.0)
Requirement already satisfied: pyinstaller==5.3 in /home/jokergamer/.local/lib/python3.10/site-packages (from -r requirements.txt (line 9)) (5.3)
Requirement already satisfied: pyinstaller-hooks-contrib==2022.8 in /home/jokergamer/.local/lib/python3.10/site-packages (from -r requirements.txt (line 10)) (2022.8)
Requirement already satisfied: pywin32-ctypes==0.2.0 in /home/jokergamer/.local/lib/python3.10/site-packages (from -r requirements.txt (line 11)) (0.2.0)
Requirement already satisfied: tinyaes==1.0.3 in /home/jokergamer/.local/lib/python3.10/site-packages (from -r requirements.txt (line 12)) (1.0.3)
Requirement already satisfied: win32-setctime==1.1.0 in /home/jokergamer/.local/lib/python3.10/site-packages (from -r requirements.txt (line 13)) (1.1.0)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from pyinstaller==5.3->-r requirements.txt (line 9)) (65.5.0)


此时进行木马免杀，输入python gen_trojan.py，结果跟一开始所提报错

在使用命令：python3.11 gen_trojan.py  
结果显示：/home/用户名/Ant-AntV/resource/
Traceback (most recent call last):
  File "/home/jokergamer/Ant-AntV/gen_trojan.py", line 9, in <module>
    from tmp_deal import create_cipher_beacon
  File "/home/jokergamer/Ant-AntV/tmp_deal.py", line 2, in <module>
    from step1 import gen_aes_payload
  File "/home/jokergamer/Ant-AntV/step1.py", line 3, in <module>
    from common.crypto_utils import crypto_utils
  File "/home/jokergamer/Ant-AntV/common/crypto_utils.py", line 3, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

实际上，使用pip list，能发现已经安装Crypto。

**Comment by shellfeel** [comment]
老哥这个是生成exe的，得在win下运行

**Comment by catunderthedusk** [comment]
> 老哥这个是生成exe的，得在win下运行

懂了，谢谢提醒，大佬。怪不得里面有个bat文件。

**Comment by catunderthedusk** [comment]
> 老哥这个是生成exe的，得在win下运行

难蚌，其实我出现的问题是生成不了木马，现在终于弄懂了，为什么程序运行不了，我用的是最新的python3.11，但大佬的这个是需要3.11版本以下的，不过现在总算成功了。

**Comment by catunderthedusk** [comment]
难搞，成功，但没完全成功。
![Screenshot 2023-01-24 220301](https://user-images.githubusercontent.com/116100663/214315226-11ca1c54-70ff-447e-b5c3-3b0e8a858390.png)

**Comment by zhangfeihub** [comment]
和你情况一样，不知道该怎么解决

**Comment by shellfeel** [comment]
> 难搞，成功，但没完全成功。 ![Screenshot 2023-01-24 220301](https://user-images.githubusercontent.com/116100663/214315226-11ca1c54-70ff-447e-b5c3-3b0e8a858390.png)

这个貌似和pyinstaller版本有关 可以尝试下

**Comment by smilexxfire** [comment]
我也遇到了这个问题
![image](https://github.com/shellfeel/Ant-AntV/assets/50986622/76ce34da-97cb-4607-ac9e-02bf71976b28)
windows pro没问题，windows server2019运行报图上的错

**Comment by smilexxfire** [comment]
step2.py中加入from sys import exit

> 我也遇到了这个问题 ![image](https://user-images.githubusercontent.com/50986622/246616716-76ce34da-97cb-4607-ac9e-02bf71976b28.png) windows pro没问题，windows server2019运行报图上的错

step2.py中加入from sys import exit可解决，但是现在程序不报错，运行后进程自动退出

**Comment by shellfeel** [comment]
> 

是不是在虚拟机下运行的？ 会简单检测虚拟机的然后直接退出的

**Comment by smilexxfire** [comment]
> > 
> 
> 是不是在虚拟机下运行的？ 会简单检测虚拟机的然后直接退出的

应该是存在sxf edr的原因，我把检测虚拟机的逻辑删除后成功上线了

**Comment by ybmgq** [comment]
![image](https://github.com/shellfeel/Ant-AntV/assets/19555929/0a6e0c83-789a-4725-8145-1e71a3c56756)

**Comment by ybmgq** [comment]
> ![image](https://user-images.githubusercontent.com/19555929/267146198-0a6e0c83-789a-4725-8145-1e71a3c56756.png)

![image](https://github.com/shellfeel/Ant-AntV/assets/19555929/03c9575e-1a52-43d7-8fe0-d1af959b3e8d)

**Comment by ybmgq** [comment]
成功了 就是不上线 打开就闪退了！
![image](https://github.com/shellfeel/Ant-AntV/assets/19555929/225c846c-3505-45a8-aca6-5baf1c24732e)

**Comment by ybmgq** [comment]
> > 难搞，成功，但没完全成功。 ![Screenshot 2023-01-24 220301](https://user-images.githubusercontent.com/116100663/214315226-11ca1c54-70ff-447e-b5c3-3b0e8a858390.png)
> 
> 这个貌似和pyinstaller版本有关 可以尝试下

你可以试试用py38
