### ISSUE TITLE
师傅，提示找不到路径是什么问题呢

### ISSUE THREAD

**Issue by ouyangningdong** [shellfeel/Ant-AntV#2]
"D:\tools\Ant-AntV-main\Ant-AntV-main\venv\Scripts\pyinstaller.exe" --clean -F -w "D:\tools\Ant-AntV-main\Ant-AntV-main/step3.py" --key "2b2390cdd23479a1" --specpath "D:\tools\Ant-AntV-main\Ant-AntV-main\spec"  -n "mail_update_2b239" --upx-dir="D:\tools\Ant-AntV-main\Ant-AntV-main\resource\upx\upx.exe"
出错啦
系统找不到指定的路径。

**Comment by ouyangningdong** [comment]
还是没搞懂

**Comment by shellfeel** [comment]
已经修复拉，重新拉下代码即可，忘了兼容非虚拟环境的情况
