### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by zhudaji** [shellfeel/Ant-AntV#6]
你好作者，我是小白，请问怎么让生成出来的程序需要管理员运行？谢谢！

**Comment by RiskySignal** [comment]
用python在运行之前判断一下是否是管理员呗；
https://blog.csdn.net/weixin_30526593/article/details/97208460
https://blog.csdn.net/linxue110/article/details/124636551

**Comment by zhudaji** [comment]
好的谢谢，请问您有好用的exe捆绑器吗

**Comment by zhudaji** [comment]
如果判断为1，如何使生成出的exe需要管理员权限运行呢？

**Comment by RiskySignal** [comment]
pyinstaller 设置 ”--uac-admin“ 啊
朋友，多搜一搜呀

**Comment by zhudaji** [comment]
非常感谢

**Comment by zhudaji** [comment]
我成功的给予了管理员权限，但居然报毒了qwq

**Comment by zhudaji** [comment]
好吧是我的疏忽，并没有报毒

**Comment by zhudaji** [comment]
360目前报毒

**Comment by RiskySignal** [comment]
我这边离线测试的，挂的CS的马，未加管理员权限，360不报毒；不清楚联网云查杀怎么样；
你那边报毒的类型是什么？

**Comment by zhudaji** [comment]
我刚才又试了一下，应该是我的域名被360标记了，所以报毒

**Comment by shellfeel** [comment]
刚测试了下还是可用的

**Comment by 1SIX1** [comment]
> 好的谢谢，请问您有好用的exe捆绑器吗

你有好用的exe捆绑器吗，将两个exe捆绑成一个exe
